version: '3.8'

services:
    # 🗄️ ClickHouse Analytics Database
    clickhouse:
        image: clickhouse/clickhouse-server:23.8
        container_name: clickhouse
        restart: always
        ports:
            - '8123:8123'
            - '9000:9000'
        environment:
            CLICKHOUSE_DB: cryptobridge
            CLICKHOUSE_USER: analytics
            CLICKHOUSE_PASSWORD: analytics123
            CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
        volumes:
            - clickhouse_data:/var/lib/clickhouse
            - clickhouse_logs:/var/log/clickhouse-server
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        networks:
            - cryptobridge-network

    # 📊 Metabase Business Intelligence
    metabase:
        image: metabase/metabase:latest
        container_name: metabase
        restart: always
        depends_on:
            - clickhouse
            - metabase-db
        ports:
            - '3000:3000'
        environment:
            MB_DB_TYPE: postgres
            MB_DB_DBNAME: metabase
            MB_DB_PORT: 5432
            MB_DB_USER: metabase
            MB_DB_PASS: metabase123
            MB_DB_HOST: metabase-db
            MB_JETTY_HOST: 0.0.0.0
            JAVA_TOOL_OPTIONS: -Xmx2g
        volumes:
            - metabase_data:/metabase-data
        networks:
            - cryptobridge-network

    # 🗃️ PostgreSQL for Metabase metadata
    metabase-db:
        image: postgres:14
        container_name: metabase-db
        restart: always
        environment:
            POSTGRES_DB: metabase
            POSTGRES_USER: metabase
            POSTGRES_PASSWORD: metabase123
        volumes:
            - metabase_postgres_data:/var/lib/postgresql/data
        networks:
            - cryptobridge-network

volumes:
    clickhouse_data:
    clickhouse_logs:
    metabase_data:
    metabase_postgres_data:

networks:
    cryptobridge-network:
        driver: bridge
